### PR TITLE
Fixed import address of minimax and corrected README's information

### PR DESCRIPTION
**Pull request by GaryHilares**
- Changed the adress to import minimax from `minimax.algorithm` to `checkers.minimax.algorithm`, change which should solve issue #1.

### CODE REVIEW

**Comment by GaryHilares** [comment]
I have made commit adding these changes:
- Corrected the command of Windows based operating systems from `python main_windows.py` to `python main.py`, change which should solve issue #3.

**Comment by GaryHilares** [comment]
I have made commit adding these changes:
- Moved `main()` in `main.py` to a conditional statement to prevent the game from running until is called when the module is imported, change which goes towards solving issue #6.
- Moved global scope code to main in `main.py`, change which should solve issue #6.

**Comment by starlightknown** [comment]
> I have made commit adding these changes:
> 
>     * Moved `main()` in `main.js` to a conditional statement to prevent the game from running until is called when the module is imported, change which goes towards solving issue #6.
> 
>     * Moved global scope code to main in `main.js`, change which should solve issue #6.

um there's no `main.js` did you mean main.py?

**Comment by GaryHilares** [comment]
Yes, it was `main.py`. Sorry for the confusion.

**Comment by starlightknown** [comment]
Solved the conflict, looks good now 
Thank you so much

**Pull request merged**
